[package]
name = "egg-netlist-synthesizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.9.3"
serde_json = "1.0.96"
serde = { version = "1.0", features = ["derive"] }
